CREATE TABLE "public"."b1_activity" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME "public"."log_activity_id_seq") NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "date"       date,
  "time"       time without time zone,
  "email"      character varying,
  "fiture"     character varying,
  CONSTRAINT "log_activity_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."b1_activity"
  ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE "public"."b1_activity" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."b1_activity" TO "anon";

REVOKE ALL ON TABLE "public"."b1_activity" FROM "authenticated";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."b1_activity" TO "authenticated";

REVOKE ALL ON TABLE "public"."b1_activity" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."b1_activity" TO "postgres";

REVOKE ALL ON TABLE "public"."b1_activity" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."b1_activity" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."log_activity_id_seq" FROM "anon";

REVOKE ALL ON SEQUENCE "public"."log_activity_id_seq" FROM "authenticated";

REVOKE ALL ON SEQUENCE "public"."log_activity_id_seq" FROM "service_role";
