CREATE TABLE "public"."d3_attendance_corrections" (
  "id"                 bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at"         timestamp with time zone NOT NULL DEFAULT now(),
  "attendance_id"      uuid                     DEFAULT gen_random_uuid(),
  "requested_by"       uuid                     DEFAULT gen_random_uuid(),
  "correction_type"    character varying,
  "proposed_clock_in"  timestamp with time zone,
  "proposed_clock_out" timestamp with time zone,
  "reason"             text,
  "status"             character varying,
  "reviewed_by"        uuid                     DEFAULT gen_random_uuid(),
  "review_note"        text,
  CONSTRAINT "d3_attendance_corrections_pkey" PRIMARY KEY (id),
  CONSTRAINT "fk_d3_attendance_corrections_d3_attendances" FOREIGN KEY (attendance_id) REFERENCES public.d3_attendances(id) ON DELETE CASCADE
);

ALTER TABLE "public"."d3_attendance_corrections"
  ENABLE ROW LEVEL SECURITY;

CREATE POLICY "D3 attendance corrections insert v1" ON "public"."d3_attendance_corrections"
  FOR INSERT
  TO "authenticated"
  WITH CHECK (((requested_by = public.d3_current_employee_uuid()) AND (EXISTS ( SELECT 1
   FROM public.d3_attendances attendance
  WHERE ((attendance.id = d3_attendance_corrections.attendance_id) AND (attendance.employee_id = public.d3_current_employee_uuid()))))));

CREATE POLICY "D3 attendance corrections select v1" ON "public"."d3_attendance_corrections"
  FOR SELECT
  TO "authenticated"
  USING
    (((public.d3_current_role() = ANY (ARRAY['HR'::public.d3_app_role, 'MANAGER'::public.d3_app_role])) OR (requested_by = public.d3_current_employee_uuid()) OR (EXISTS ( SELECT 1
   FROM public.d3_attendances attendance
  WHERE ((attendance.id = d3_attendance_corrections.attendance_id) AND (attendance.employee_id = public.d3_current_employee_uuid()))))));

CREATE POLICY "D3 attendance corrections update v1" ON "public"."d3_attendance_corrections"
  FOR UPDATE
  TO "authenticated"
  USING ((public.d3_current_role() = ANY (ARRAY['HR'::public.d3_app_role, 'MANAGER'::public.d3_app_role])))
  WITH CHECK ((public.d3_current_role() = ANY (ARRAY['HR'::public.d3_app_role, 'MANAGER'::public.d3_app_role])));

REVOKE ALL ON TABLE "public"."d3_attendance_corrections" FROM "anon";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."d3_attendance_corrections" TO "anon";

REVOKE ALL ON TABLE "public"."d3_attendance_corrections" FROM "authenticated";

GRANT INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."d3_attendance_corrections" TO "authenticated";

REVOKE ALL ON TABLE "public"."d3_attendance_corrections" FROM "postgres";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."d3_attendance_corrections" TO "postgres";

REVOKE ALL ON TABLE "public"."d3_attendance_corrections" FROM "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."d3_attendance_corrections" TO "service_role";

REVOKE ALL ON SEQUENCE "public"."d3_attendance_corrections_id_seq" FROM "anon";

REVOKE ALL ON SEQUENCE "public"."d3_attendance_corrections_id_seq" FROM "authenticated";

REVOKE ALL ON SEQUENCE "public"."d3_attendance_corrections_id_seq" FROM "service_role";
