"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertCircle, CalendarDays, RefreshCw, TrendingDown, TrendingUp } from "lucide-react";

type Point = { period_month: string; revenue: number; cost: number; sales_profit: number; total_outstanding: number };
type Payload = { data: { period: { start_period: string; end_period: string }; summary: { revenue: number; cost: number; sales_profit: number; total_outstanding: number } | null; series: Point[] } };
const money = new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 });
const month = () => { const d = new Date(); return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, "0")}`; };
const shift = (value: string, amount: number) => { const d = new Date(`${value}-01T00:00:00Z`); d.setUTCMonth(d.getUTCMonth() + amount); return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, "0")}`; };

export default function SalesOverviewPage() {
  const endDefault = useMemo(() => month(), []);
  const [start, setStart] = useState(() => shift(endDefault, -2));
  const [end, setEnd] = useState(endDefault);
  const [payload, setPayload] = useState<Payload["data"] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const response = await fetch(`/api/v1/analytics/macro?start_period=${start}&end_period=${end}`, { cache: "no-store" }); const body = await response.json() as Payload & { error?: { message?: string } }; if (!response.ok) throw new Error(body.error?.message ?? "Data Sales Overview gagal dimuat."); setPayload(body.data); } catch (reason) { setPayload(null); setError(reason instanceof Error ? reason.message : "Data Sales Overview gagal dimuat."); } finally { setLoading(false); } }, [end, start]);
  useEffect(() => {
    const timer = window.setTimeout(() => void load(), 0);
    return () => window.clearTimeout(timer);
  }, [load]);
  const summary = payload?.summary;
  return <main className="min-h-dvh bg-[#f4f6f8] px-4 py-6 text-[#172033] sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><header className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#536b89]">CCR / ANALYTICS</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight">Sales Overview</h1><p className="mt-1 text-sm text-slate-500">Ringkasan revenue, cost, dan outstanding tervalidasi.</p></div><div className="flex flex-wrap items-end gap-2"><PeriodInput label="Mulai" value={start} max={end} onChange={setStart} disabled={loading} /><PeriodInput label="Sampai" value={end} min={start} onChange={setEnd} disabled={loading} /><button type="button" onClick={() => void load()} disabled={loading} className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#183866] px-3 text-xs font-bold text-white disabled:opacity-60"><RefreshCw size={14} className={loading ? "animate-spin" : ""} /> Refresh</button></div></header>{error ? <ErrorState message={error} onRetry={() => void load()} /> : loading ? <><MetricSkeletons /><ChartSkeleton /></> : !payload?.series.length ? <EmptyState /> : <><div className="grid gap-4 md:grid-cols-3"><MetricCard label="Sales Profit Bulanan" value={money.format(summary?.sales_profit ?? 0)} detail={`Revenue ${money.format(summary?.revenue ?? 0)}`} positive={(summary?.sales_profit ?? 0) >= 0} /><MetricCard label="Kebutuhan Cost Bulanan" value={money.format(summary?.cost ?? 0)} detail="Cost tervalidasi" positive={false} /><MetricCard label="Total Outstanding" value={money.format(summary?.total_outstanding ?? 0)} detail="Tagihan belum dibayar" positive={false} /></div><TrendChart series={payload.series} /></>}</div></main>;
}

function PeriodInput({ label, value, min, max, onChange, disabled }: { label: string; value: string; min?: string; max?: string; onChange: (value: string) => void; disabled: boolean }) { return <label className="flex h-10 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 text-xs text-slate-500"><CalendarDays size={14} /><span>{label}</span><input type="month" value={value} min={min} max={max} onChange={(event) => onChange(event.target.value)} disabled={disabled} className="bg-transparent font-semibold text-slate-700 outline-none disabled:opacity-50" /></label>; }
function MetricCard({ label, value, detail, positive }: { label: string; value: string; detail: string; positive: boolean }) { return <section className="min-h-32 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-500">{label}</p><span className={`grid size-8 place-items-center rounded-lg ${positive ? "bg-emerald-100 text-emerald-700" : "bg-blue-100 text-blue-700"}`}>{positive ? <TrendingUp size={16} /> : <TrendingDown size={16} />}</span></div><p className="mt-4 text-2xl font-extrabold tracking-tight text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-500">{detail}</p></section>; }
function TrendChart({ series }: { series: Point[] }) { const max = Math.max(...series.flatMap((point) => [point.revenue, point.cost, point.total_outstanding]), 1); const width = 760; const height = 260; const x = (i: number) => series.length === 1 ? width / 2 : 24 + i * (width - 48) / (series.length - 1); const y = (v: number) => height - 24 - v / max * (height - 48); const path = (key: "revenue" | "cost" | "total_outstanding") => series.map((point, i) => `${i ? "L" : "M"}${x(i)},${y(point[key])}`).join(" "); return <section className="mt-5 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-base font-bold text-slate-900">Pergerakan Revenue, Cost & Outstanding</h2><p className="mt-1 text-xs text-slate-500">Tren bulanan dari data tervalidasi.</p></div><div className="flex gap-3 text-xs text-slate-500"><Legend color="#0f766e" label="Revenue" /><Legend color="#2563eb" label="Cost" /><Legend color="#dc2626" label="Outstanding" /></div></div><div className="mt-6 overflow-x-auto"><svg viewBox={`0 0 ${width} ${height}`} className="h-64 min-w-[600px] w-full" role="img" aria-label="Grafik tren revenue, cost, dan outstanding"><line x1="24" y1={height - 24} x2={width - 24} y2={height - 24} stroke="#cbd5e1" /><line x1="24" y1="24" x2="24" y2={height - 24} stroke="#cbd5e1" />{series.map((point, i) => <text key={point.period_month} x={x(i)} y={height - 6} textAnchor="middle" className="fill-slate-400 text-[10px]">{point.period_month}</text>)}<path d={path("revenue")} fill="none" stroke="#0f766e" strokeWidth="3" strokeLinecap="round" /><path d={path("cost")} fill="none" stroke="#2563eb" strokeWidth="3" strokeLinecap="round" /><path d={path("total_outstanding")} fill="none" stroke="#dc2626" strokeWidth="3" strokeLinecap="round" /></svg></div></section>; }
function Legend({ color, label }: { color: string; label: string }) { return <span className="inline-flex items-center gap-1.5"><i className="size-2 rounded-full" style={{ backgroundColor: color }} />{label}</span>; }
function MetricSkeletons() { return <div className="grid gap-4 md:grid-cols-3">{[1, 2, 3].map((item) => <div key={item} className="h-32 animate-pulse rounded-xl border border-slate-200 bg-white p-5"><div className="h-3 w-32 rounded bg-slate-200" /><div className="mt-6 h-7 w-40 rounded bg-slate-200" /><div className="mt-2 h-3 w-28 rounded bg-slate-200" /></div>)}</div>; }
function ChartSkeleton() { return <div className="mt-5 h-96 animate-pulse rounded-xl border border-slate-200 bg-white p-5"><div className="h-5 w-72 rounded bg-slate-200" /><div className="mt-10 h-64 rounded bg-slate-100" /></div>; }
function EmptyState() { return <div className="rounded-xl border border-dashed border-slate-300 bg-white px-6 py-20 text-center"><p className="font-bold text-slate-700">Belum ada data tervalidasi</p><p className="mt-2 text-sm text-slate-500">Sales Overview akan tampil setelah data diproses dan divalidasi.</p></div>; }
function ErrorState({ message, onRetry }: { message: string; onRetry: () => void }) { return <div className="rounded-xl border border-red-200 bg-red-50 px-6 py-12 text-center"><AlertCircle className="mx-auto text-red-600" size={28} /><p className="mt-3 font-bold text-red-800">Data tidak dapat dimuat</p><p className="mt-1 text-sm text-red-700">{message}</p><button type="button" onClick={onRetry} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-red-700 px-4 py-2 text-xs font-bold text-white"><RefreshCw size={14} /> Coba lagi</button></div>; }
