import { OverdueInvoiceItem, OverdueKpiSummary } from '@/types/overdue';

export const INITIAL_OVERDUE_KPI: OverdueKpiSummary = {
  totalOverdueValue: 8420000000,
  totalOverdueValueGrowth: 12.4,
  affectedInvoicesCount: 48,
  criticalAgingValue: 3150000000,
  criticalAgingPercent: 37.4,
  criticalDebtorsCount: 14,
  avgDsoDelay: 38.2,
  slaDiff: 8.2,
  targetRecoveryDays: 24,
  unassignedPicCount: 9,
  unassignedFloatingValue: 1480000000,
};

export const INITIAL_OVERDUE_INVOICES: OverdueInvoiceItem[] = [
  {
    id: 'inv-8841',
    invoice_number: 'INV-2026/07-8841',
    customer_id: 'CUST-0841',
    customer_name: 'PT Samudera Perkasa Nusantara',
    npwp: '01.482.912.4-501.000',
    branch: 'Semarang',
    branch_code: 'SMR-02',
    due_date: '15 Juli 2026',
    amount_overdue: 1250000000,
    payment_note: 'Belum Ada Pembayaran',
    days_overdue: 75,
    risk_status: 'LEGAL ESCALATION',
    pic_assigned: 'Hendra K.',
    pic_initials: 'HK',
    action_type: 'SP-2',
    contact_person: {
      name: 'Bambang Wicaksono',
      role: 'Finance Director',
      phone: '+62 811-294 8812',
    },
    last_log: {
      date: '28 Jul',
      time: '14:15',
      text: 'Janji bayar via transfer bilyet giro tgl 28 Juli belum terealisasi di rekening koran Mandiri. Alasan kendala approval direksi pusat.',
      logged_by: 'Hendra Kusuma',
    },
    route: 'Tanjung Perak to Balikpapan Haulage',
  },
  {
    id: 'inv-9102',
    invoice_number: 'INV-2026/08-9102',
    customer_id: 'CUST-0919',
    customer_name: 'CV Bintang Borneo Abadi',
    npwp: '02.910.482.1-702.000',
    branch: 'Balikpapan',
    branch_code: 'BPN-01',
    due_date: '22 Juli 2026',
    amount_overdue: 840000000,
    payment_note: 'DP 20% Dibayar',
    days_overdue: 68,
    risk_status: 'HIGH RISK',
    pic_assigned: undefined,
    action_type: 'TUGASKAN',
    contact_person: {
      name: 'Handoko Sugiarto',
      role: 'Managing Director',
      phone: '+62 812-500 1122',
    },
    last_log: {
      date: '15 Aug',
      time: '10:30',
      text: 'Pembayaran DP 20% diterima, sisa tagihan menunggu pengapalan berikutnya.',
      logged_by: 'System Audit',
    },
    route: 'Kariangau BPN to Makassar Freight',
  },
  {
    id: 'inv-9844',
    invoice_number: 'INV-2026/08-9844',
    customer_id: 'CUST-0192',
    customer_name: 'Aurora Blue Kargo Logistik',
    npwp: '01.345.890.1-021.000',
    branch: 'Jakarta Port',
    branch_code: 'JKT-03',
    due_date: '05 Agustus 2026',
    amount_overdue: 645000000,
    payment_note: 'Dispute Biaya Demurrage',
    days_overdue: 54,
    risk_status: 'WATCHLIST',
    pic_assigned: 'Deni S.',
    pic_initials: 'DS',
    action_type: 'AUDIT',
    contact_person: {
      name: 'Siska Melati',
      role: 'Finance Manager',
      phone: '+62 21 5082 1199',
    },
    last_log: {
      date: '20 Aug',
      time: '11:00',
      text: 'Pengajuan klaim bebas demurrage 7 hari sedang direvisi tim legal.',
      logged_by: 'Deni Setiawan',
    },
    route: 'Tanjung Priok to Tanjung Perak',
  },
  {
    id: 'inv-9912',
    invoice_number: 'INV-2026/08-9912',
    customer_id: 'CUST-0991',
    customer_name: 'PT Tirta Mas Multimodal',
    npwp: '03.881.092.3-601.000',
    branch: 'Surabaya',
    branch_code: 'SUB-01',
    due_date: '12 Agustus 2026',
    amount_overdue: 510000000,
    payment_note: 'Janji Bayar Ingkar',
    days_overdue: 47,
    risk_status: 'HIGH RISK',
    pic_assigned: 'Agus W.',
    pic_initials: 'AW',
    action_type: 'SP-1',
    contact_person: {
      name: 'Agus Wijaya',
      role: 'Head of Operations',
      phone: '+62 31 7733 2211',
    },
    last_log: {
      date: '25 Aug',
      time: '16:45',
      text: 'Kunjungan kantor Surabaya dilakukan. Konfirmasi cek mundur tgl 05 Oktober.',
      logged_by: 'Agus W.',
    },
    route: 'Tanjung Perak to Bitung Route',
  },
  {
    id: 'inv-1002',
    invoice_number: 'INV-2026/08-1002',
    customer_id: 'CUST-1002',
    customer_name: 'PT Belawan Raya Translog',
    npwp: '04.771.829.2-101.000',
    branch: 'Belawan',
    branch_code: 'BLW-01',
    due_date: '20 Agustus 2026',
    amount_overdue: 390000000,
    payment_note: 'Pengecekan Faktur Pajak',
    days_overdue: 39,
    risk_status: 'WATCHLIST',
    pic_assigned: undefined,
    action_type: 'TUGASKAN',
    contact_person: {
      name: 'Rudi Hartono',
      role: 'Tax Specialist',
      phone: '+62 61 451 8899',
    },
    last_log: {
      date: '01 Sep',
      time: '09:15',
      text: 'Permintaan e-faktur revisi telah dikirimkan ke bagian keuangan.',
      logged_by: 'System Audit',
    },
    route: 'Belawan Medan to Tanjung Priok',
  },
  {
    id: 'inv-1025',
    invoice_number: 'INV-2026/08-1025',
    customer_id: 'CUST-1025',
    customer_name: 'PT Bahtera Nusantara Pasifik',
    npwp: '05.662.910.1-011.000',
    branch: 'Jakarta',
    branch_code: 'JKT-01',
    due_date: '25 Agustus 2026',
    amount_overdue: 480000000,
    payment_note: 'Termin Khusus 45 Hari',
    days_overdue: 34,
    risk_status: 'NEGOSIASI',
    pic_assigned: 'Hendra K.',
    pic_initials: 'HK',
    action_type: 'TERMIN',
    contact_person: {
      name: 'Surya Kencana',
      role: 'Treasury Lead',
      phone: '+62 21 4390 5544',
    },
    last_log: {
      date: '10 Sep',
      time: '14:00',
      text: 'Kesepakatan rescheduling termin 45 hari disetujui VP Finance.',
      logged_by: 'Hendra Kusuma',
    },
    route: 'Tanjung Priok to Kariangau BPN',
  },
  {
    id: 'inv-1090',
    invoice_number: 'INV-2026/08-1090',
    customer_id: 'CUST-1090',
    customer_name: 'PT Cipta Sarana Maritim',
    npwp: '06.551.440.8-502.000',
    branch: 'Semarang',
    branch_code: 'SMR-01',
    due_date: '27 Agustus 2026',
    amount_overdue: 275000000,
    payment_note: 'Faktur Retensi Kontrak',
    days_overdue: 32,
    risk_status: 'WATCHLIST',
    pic_assigned: 'Deni S.',
    pic_initials: 'DS',
    action_type: 'AUDIT',
    contact_person: {
      name: 'Eko Prasetyo',
      role: 'Contract Manager',
      phone: '+62 24 8491 7766',
    },
    last_log: {
      date: '18 Sep',
      time: '13:20',
      text: 'Pemeriksaan klausul retensi 5% proyek angkutan barang berat.',
      logged_by: 'Deni Setiawan',
    },
    route: 'Tanjung Emas to Tanjung Perak',
  },
  {
    id: 'inv-1115',
    invoice_number: 'INV-2026/08-1115',
    customer_id: 'CUST-1115',
    customer_name: 'CV Khatulistiwa Logistikindo',
    npwp: '07.442.119.5-602.000',
    branch: 'Surabaya',
    branch_code: 'SUB-02',
    due_date: '28 Agustus 2026',
    amount_overdue: 230000000,
    payment_note: 'Bongkar Muat Dermaga 4',
    days_overdue: 31,
    risk_status: 'WATCHLIST',
    pic_assigned: undefined,
    action_type: 'TUGASKAN',
    contact_person: {
      name: 'Agus Setiawan',
      role: 'Logistics Supervisor',
      phone: '+62 31 7733 8844',
    },
    last_log: {
      date: '22 Sep',
      time: '15:10',
      text: 'Dokumen STPF rampung divalidasi otoritas dermaga.',
      logged_by: 'System Audit',
    },
    route: 'Tanjung Perak to Makassar',
  },
];
